export const UserActions = {
    REGISTER: "REGISTER",
    LOGIN: "LOGIN",
    LOAD_USER:"LOAD_USER",
    DELETE_USER: "DELETE_USER",
    LOADING:"LOADING",
    CLEAR_USER: "CLEAR_USER",
    EDIT_USER:"EDIT_USER"
}