export const ItemActions = {
    DISPLAY: "DISPLAY",
    REMOVE_ITEM: "REMOVE_ITEM",
    ADD_ITEM: "ADD_ITEM",
    INCREASE: "INCREASE",
    DECREASE: "DECREASE",
    NOT_FOUND: "NOT_FOUND",
    FOUND: "FOUND",
    CLEAR_CART:'CLEAR_CART'
}