export const ItemActions = {
    DISPLAY: "DISPLAY",
    REMOVE_ITEM: "REMOVE_ITEM",
    ADD_ITEM: "ADD_ITEM",
    EDIT_ITEM: "EDIT_ITEM",
    INCREASE: "INCREASE",
    DECREASE: "DECREASE",
    NOT_FOUND: "NOT_FOUND",
    DONE: "DONE",
    CLEAR_CART:'CLEAR_CART'
}